apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-httpbin-same-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-same-ns
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: httpbin-same-ns
    spec:
      containers:
      - name: httpbin
        image: mrnim94/httpbin
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /status/200
            port: 80
        readinessProbe:
          httpGet:
            path: /status/200
            port: 80