---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: busybox-other-ns-sa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-other-ns-deployment
  labels:
    app: busybox-other-ns
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox-other-ns
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: busybox-other-ns
    spec:
      containers:
      - name: busybox
        image: mrnim94/busybox-curl
        imagePullPolicy: IfNotPresent
        
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
      serviceAccountName: busybox-other-ns-sa